NVIDIA/k8s-device-plugin

- README.md
- RELEASE.md
- deployments/helm/nvidia-device-plugin/Chart.yaml
- deployments/static/extensions-v1beta1-nvidia-device-plugin.yml
- deployments/static/nvidia-device-plugin-compat-with-cpumanager.yml
- deployments/static/nvidia-device-plugin-privileged-with-service-account.yml
- nvidia-device-plugin.yml
- versions.mk
Cherry-picks changes from https://github.com/NVIDIA/k8s-device-plugin/pull/487
> Update version on main to v0.14.4

- internal/plugin/server.go
restartCount starts with 0, before, we'll crash 7 times then quit. Now, we'll quit at 6th.
/kind bug
> Fix: counting server restart times error

- deployments/helm/nvidia-device-plugin/templates/daemonset-mps-control-daemon.yml
- internal/lm/nvml.go
- internal/lm/nvml_test.go
- tests/e2e/gpu-feature-discovery_test.go
- tests/expected-output-mig-mixed.txt
- tests/expected-output-mig-none.txt
- tests/expected-output-mig-single.txt
- tests/expected-output.txt
> Rename nvidia.com/sharing.mps.enabled to nvidia.com/mps.capable

- README.md
> Update nvidia-container-toolkit instructions

- README.md
- RELEASE.md
- deployments/helm/nvidia-device-plugin/Chart.yaml
- deployments/static/extensions-v1beta1-nvidia-device-plugin.yml
- deployments/static/nvidia-device-plugin-compat-with-cpumanager.yml
- deployments/static/nvidia-device-plugin-privileged-with-service-account.yml
- nvidia-device-plugin.yml
- versions.mk
This change cherry picks the CUDA verison bump from #563 and bumps the version to v0.14.5.
> Cherry pick v0.14.5

- Makefile
This change uses build flags consistently and allows builds and tests on Darwin.
> Allow builds and tests on Darwin

- .github/workflows/image.yaml
This removes:
* 6cb877e54b7a42e4071ba29a9bd30867ae44d2b9
* 9df65b57225e6c3c8686282aedc8bb3e752bf711
added to test #636
> Remove accidental CI changes

- tests/e2e/common/kubernetes.go
- tests/e2e/gpu-feature-discovery_test.go
> E2E test: Ommit error ifNotFound during NFD cleanup

- internal/lm/resource.go
- internal/lm/resource_test.go
> strip parentheses from the gpu product name

- .common-ci.yml
- .nvidia-ci.yml
add ngc image signing job for auto signing
> add ngc image signing job for auto signing

- .github/workflows/release.yaml
- RELEASE.md
- hack/create-release.sh
- hack/generate-changelog.sh
- hack/prepare-release.sh
- hack/update-helm-index.sh
These changes address issues with the release process.
> [no-relnotes] Fix release scripts

- CHANGELOG.md
- cmd/mps-control-daemon/mount/mount-shm.go
- deployments/container/Makefile
- deployments/helm/nvidia-device-plugin/templates/_helpers.tpl
- deployments/helm/nvidia-device-plugin/templates/daemonset-device-plugin.yml
- deployments/helm/nvidia-device-plugin/templates/daemonset-gfd.yml
- deployments/helm/nvidia-device-plugin/templates/daemonset-mps-control-daemon.yml
- deployments/helm/nvidia-device-plugin/templates/role-binding.yml
- deployments/helm/nvidia-device-plugin/templates/role.yml
- deployments/helm/nvidia-device-plugin/templates/service-account.yml
- internal/lm/nvml.go
- internal/lm/nvml_test.go
Cherry-pick the following changes:
* #748 
* #713 
* #542
* #765
> Cherry pick changes for v0.15.1

- README.md
- deployments/helm/nvidia-device-plugin/Chart.yaml
- deployments/static/gpu-feature-discovery-daemonset-with-mig-mixed.yaml
- deployments/static/gpu-feature-discovery-daemonset-with-mig-single.yaml
- deployments/static/gpu-feature-discovery-daemonset.yaml
- deployments/static/gpu-feature-discovery-job.yaml.template
- deployments/static/nvidia-device-plugin-compat-with-cpumanager.yml
- deployments/static/nvidia-device-plugin.yml
- versions.mk
This includes the changes from #755 
See https://github.com/NVIDIA/cloud-native-team/issues/76
> Bump version for release v0.15.1

- .github/workflows/publish-helm.yaml
> [no-relnote] Set GH_TOKEN for helm publish step

- CHANGELOG.md
- README.md
- deployments/helm/nvidia-device-plugin/Chart.yaml
- deployments/static/gpu-feature-discovery-daemonset-with-mig-mixed.yaml
- deployments/static/gpu-feature-discovery-daemonset-with-mig-single.yaml
- deployments/static/gpu-feature-discovery-daemonset.yaml
- deployments/static/gpu-feature-discovery-job.yaml.template
- deployments/static/nvidia-device-plugin-compat-with-cpumanager.yml
- deployments/static/nvidia-device-plugin.yml
- versions.mk
This cherry-picks the release changes from #882 to `main`.
> Bump release v0.16.2

- tests/e2e/gpu-feature-discovery_test.go
This backports the changes from #923
> [no-relnote] Fix typo in log collection tooling

- cmd/nvidia-device-plugin/main.go
This fixes a bug introduced in #991
> Fix setting of kubelet socket

- .golangci.yml
- deployments/container/Dockerfile.ubi8
- deployments/container/Dockerfile.ubuntu
> Update GOLANG_VERSION in Dockerfile

- .github/dependabot.yml
This chagne reorganises the dependabot definition for this repo.
> [no-relnote] Update dependabot

- deployments/helm/nvidia-device-plugin/templates/daemonset-device-plugin.yml
> Ensure FAIL_ON_INIT_ERROR boolean env is quoted

- internal/lm/resource.go
> Add ada-lovelace architecture label for compute capability 8.9

- CHANGELOG.md
- README.md
- deployments/helm/nvidia-device-plugin/Chart.yaml
- deployments/static/gpu-feature-discovery-daemonset-with-mig-mixed.yaml
- deployments/static/gpu-feature-discovery-daemonset-with-mig-single.yaml
- deployments/static/gpu-feature-discovery-daemonset.yaml
- deployments/static/gpu-feature-discovery-job.yaml.template
- deployments/static/nvidia-device-plugin-compat-with-cpumanager.yml
- deployments/static/nvidia-device-plugin.yml
- versions.mk
This change bumps the version of the GPU Device Plugin to v0.17.1.
> Bump release v0.17.1
