nvidia-device-plugin.yml
This change allows us to patch the device plugin to (for example) update the
image tag to the latest version and have an automated rolling upgrade be
performed to update the plugin on all agent nodes.
Previously, the device plugin on each node would *only* be restarted with the
new image if the pod representing it was explicitly shutdown and restarted.
=> Set the default 'updateStrategy' to 'RollingUpdate' in branch v1.11

nvidia-device-plugin.yml
This change allows us to patch the device plugin to (for example) update the
image tag to the latest version and have an automated rolling upgrade be
performed to update the plugin on all agent nodes.
Previously, the device plugin on each node would *only* be restarted with the
new image if the pod representing it was explicitly shutdown and restarted.
=> Set the default 'updateStrategy' to 'RollingUpdate' in branch v1.12

nvidia-device-plugin.yml
Use annotation and tolerations to mark pod as critical is deprecated in version 1.13 and removed in version 1.14 of Kubernetes. We need to use the priorityClassName pod attribute set as “system-cluster-critical” or “system-node-critical”.
Signed-off-by: Jordan Jacobelli <jjacobelli@nvidia.com>
=> Change how to specify pod as critical

deployments/helm/nvidia-device-plugin/templates/daemonset-device-plugin.yml, deployments/helm/nvidia-device-plugin/templates/daemonset-mps-control-daemon.yml
When deployed without MPS enabled, the device plugin fails due to mounts not being creatable.
=> Fix mps deployment

cmd/nvidia-device-plugin/main.go, cmd/nvidia-device-plugin/plugin-manager.go, internal/cdi/cdi.go, internal/cdi/options.go, internal/plugin/manager/factory.go, internal/plugin/manager/nvml.go, internal/plugin/manager/options.go, internal/plugin/manager/tegra.go, internal/plugin/server.go, internal/plugin/server_test.go
This change allows MPS to be used with the `envvar` and `volumeMounts` device list strategies.
=> Remove requirement to use CDI for MPS injection

cmd/mps-control-daemon/main.go, deployments/helm/nvidia-device-plugin/templates/daemonset-mps-control-daemon.yml, internal/rm/rm.go
This PR makes the following changes:
* Fixes a bug in the `AddDefaultResourcesToConfig` option to handle the case where the `mig-strategy` is not set. This happens in the case of the MPS control daemon daemonset when a `nvidia.com/sharing.mps.enabled=true` label is present, but no config map is used.
* Fixes a crashloop in the MPS control daemon due to a failing startup probe when no MPS devices are present. This switches to a global `.ready` file for indicating readiness instead of a per-resource file.
=> Fix mps control daemon crashloop

api/config/v1/flags.go, cmd/mps-control-daemon/mps/daemon.go, cmd/mps-control-daemon/mps/manager.go, cmd/mps-control-daemon/mps/root.go, cmd/nvidia-device-plugin/main.go, deployments/helm/nvidia-device-plugin/templates/daemonset-device-plugin.yml, deployments/helm/nvidia-device-plugin/templates/daemonset-mps-control-daemon.yml, deployments/helm/nvidia-device-plugin/values.yaml, internal/plugin/server.go
This change allows the MPS root on the host to be specified and uses /run/nvidia/mps by default.
This requires #516
=> Allow mps root to be specified

cmd/mps-control-daemon/mps/manager.go, deployments/helm/nvidia-device-plugin/templates/daemonset-mps-control-daemon.yml, internal/lm/nvml.go, internal/lm/nvml_test.go, internal/plugin/manager/nvml.go, internal/plugin/manager/tegra.go, internal/plugin/server.go
This PR cleans up a number of aspects around MPS. Namely:
* Removes the MPS log dir from the workload
* Disable MPS for MIG
* Fixes an incorrect conditional check for MPS
=> MPS cleanup

README.md
Closes https://github.com/NVIDIA/cloud-native-team/issues/19
=> Add MPS sharing section to README

.nvidia-ci.yml
This change pulls the ghcr.io image instead of the GitLab image.
=> Use github image as staging image

.github/dependabot.yml
See also https://github.com/helm/helm/pull/12356 where this was changed to list the dependencies explicitly.
=> Update k8s.io dependencies as a group

.github/workflows/stale.yaml
Default is 30, our average per repo issue + PR number is around 200+ , 300 is a reasonable threshold
=> Increase operations-per-run on stale action

.github/workflows/golang.yaml, Makefile, go.mod, versions.mk
This PR updates the golang actions to use the GOLANG_VERSION defined in versions.mk
This ensures consistency between what is built for the images and what is tested in CI. 
It also adds a `vendor` and `check-vendor` make target to ensure that the local go module files are up to date.
=> Extract GOLANG_VERSION from versions.mk

go.mod, vendor/modules.txt
The replace directives aren't needed. This change does not alter the `go.sum` checksums, so the dependency tree is maintained as-is
This improves readability of the go.mod and makes it easier for others to discern the dependency tree of k8s-device-plugin
=> clean up replace directives in go.mod

.github/dependabot.yml
This upates the actions used to build the helm repo.
See https://github.com/NVIDIA/k8s-device-plugin/actions/runs/8094467127 for Nodejs deprecation warnings.
=> Add dependabot config to update actions for gh-pages

CHANGELOG.md, README.md, api/config/v1/consts.go, api/config/v1/strategy.go, internal/plugin/server.go
Add `cdi-cri` device list strategy that makes use of the `CDIDevices` field in the device plugin API.
This field is internally mapped to annotation AND CRI field modifications in the kubelet.
=> Add cdi-cri device list strategy

CHANGELOG.md, cmd/mps-control-daemon/mps/daemon.go
This change switches to setting MPS memory limits by index instead of UUID.
The `nvidia-cuda-mps-control` daemon does not seem to handle the case where the NVML UUID is used to set these limits.
=> Set mps device memory limit by index

CHANGELOG.md, api/config/v1/config.go, internal/plugin/server.go, internal/rm/rm.go, internal/rm/rm_test.go
These changes refactor the sharing checks when processing a Allocate request.
The behaviour that allows `failRequestGreaterThanOne` to control whether multiple devices can be allocated is maintained for TimeSlicing, but this setting is ignored for MPS sharing.
This aligns with the behaviour for the GKE plugin with the exception that we do not "merge" partitions if multiples are requested in a single device. This can be added as a future extension (see https://github.com/NVIDIA/k8s-device-plugin/pull/586).
Closes https://github.com/NVIDIA/cloud-native-team/issues/48
=> Update sharing checks for MPS

cmd/mps-control-daemon/mps/daemon.go
This removes the log dir on stop to prevent logs from being appended to.
=> Cleanup log dir on stop

cmd/mps-control-daemon/mps/daemon.go, cmd/mps-control-daemon/mps/log-tailer.go
This change adds a background `tail -n +1 -f` command for the `control.log` associated with an MPS daemon.
This is outputed to stdout to ensure that MPS control daemon logs are also available in the `kubectl logs` output.
```
I0313 19:23:55.081285      69 daemon.go:131] "Starting log tailer" resource="nvidia.com/gpu"
[2024-03-13 19:23:55.063 Control    98] Starting control daemon using socket /mps/nvidia.com/gpu/pipe/control
[2024-03-13 19:23:55.063 Control    98] To connect CUDA applications to this daemon, set env CUDA_MPS_PIPE_DIRECTORY=/mps/nvidia.com/gpu/pipe
...
[2024-03-13 19:24:23.903 Control    98] NEW UI
[2024-03-13 19:24:23.903 Control    98] Cmd:get_default_active_thread_percentage
[2024-03-13 19:24:23.903 Control    98] 10.0
[2024-03-13 19:24:23.903 Control    98] UI closed …
```
=> Add log tailer for MPS control logs

cmd/mps-control-daemon/mps/device.go, cmd/mps-control-daemon/mps/device_test.go, cmd/mps-control-daemon/mps/manager.go, go.mod, internal/rm/device_map.go, internal/rm/devices.go, internal/rm/nvml_devices.go, internal/rm/tegra_devices.go, internal/rm/wsl_devices.go
This change ensures that the maximum number of replicase for MPS is:
* 48 on Volta or newer systems.
* 16 on older systems.
=> Enforce maximum MPS replicas

cmd/mps-control-daemon/main.go
This change ensures that a mig-strategy=none is used if no mig strategy is explicitly specified when building the map of required devices.
This also removes the need to explicitly check for nil values when querying this value.
The MPS control daemon segfaults from the operator when dereferencing the nil mig strategy value in the config:
```
I0313 12:02:08.001435     146 main.go:72] Starting NVIDIA MPS Control Daemon 40ff9bf4
I0313 12:02:08.001626     146 main.go:55] "Starting NVIDIA MPS Control Daemon" version="40ff9bf4"
I0313 12:02:08.001645     146 main.go:101] Starting OS watcher.
I0313 12:02:08.001867     146 main.go:115] Starting Daemons.
I0313 12:02:08.001901     146 main.go:158] Loading configuration.
I0313 12:02:08.002392     146 main.go:166] Updating config with default resource …
```
=> Default to mig-strategy none if not specified

internal/lm/labeler.go, internal/lm/nvml.go
The function name and error messages when creating a device labeller mentions NVML -- although NVML may not be used. This change renames the function and also makes the error message more generic.
=> Fix error message when creating labeler

.golangci.yml, internal/plugin/server_test.go, tests/e2e/e2e_test.go
To get more details on these why fixes were implemented: https://husni.dev/beware-of-implicit-memory-aliasing-in-go-foor-loop/
=> [golangci-lint] fix implicit memory aliasing in for loop 

deployments/helm/nvidia-device-plugin/values.yaml
Refer to https://kubernetes-sigs.github.io/node-feature-discovery/v0.15/reference/worker-configuration-reference#sourcespci
"02" means "02*" so the other entries starting with 02 are redundant.
Also improve compatibility by detecting all "03" types of display controllers, not just "0302". Refer to: https://admin.pci-ids.ucw.cz/read/PD/03
Also note that the default value of upstream NFD includes "03", as in this merge request. So this will improve compatibility and bring the behaviour in line with the standard defaults of upstream NFD. This way users can have the same standard expected behaviour whether they use NFD which is bundled in the NVIDIA device plugin, or upstream NFD.
=> Simplify and improve compatibility of PCI device classes for NFD workers

tests/e2e/common/diagnostics/kubernetes.go
`bufio.Scanner.Scan()` strips the newline characters by default. This change adds these back.
=> Add newline to pod logs

cmd/nvidia-device-plugin/main.go
This change aligns the container driver root envar with those used by the Container Toolkit (DRIVER_ROOT_CTR_PATH).
The command line argument is also changed to match the value used there.
=> Align container driver root envvars

internal/lm/nvml.go, internal/lm/nvml_test.go
This change raises an error in GFD if MPS sharing is enabled for MIG devices instead of (siliently) setting `nvidia.com/mps.capable=false`.
This aligns GFD behaviour with that of the device plugin.
=> Raise error in GFD when MPS sharing is enabled for MIG devices

internal/flags/node.go, internal/lm/output.go, internal/lm/vgpu.go
This change treats errors in constructing vGPU labels as warnings.
If errors occur the `nvidia.com/vgpu.present` label is set to `false` instead of raising an error.
For example, on my mac:
```
./gpu-feature-discovery --oneshot --output="" --node-name=foo
I0422 20:59:12.321562   63053 main.go:139] Starting OS watcher.
I0422 20:59:12.321919   63053 main.go:144] Loading configuration.
I0422 20:59:12.323056   63053 main.go:156]
Running with config:
{
"version": "v1",
"flags": {
"migStrategy": "none",
"failOnInitError": true,
"gdsEnabled": null,
"mofedEnabled": null,
"useNodeFeatureAPI": false,
"gfd": {
"oneshot": true,
"noTimestamp": false,
"sleepInterval": "1m0s",
"outputFile": "",
"machineTypeFile": "/sys/class/dmi/id/product_name"
}
},
"resources": {
"gpus": null
},
"sharing": { …
```
=> Make vgpu failures non-fatal

cmd/gpu-feature-discovery/main.go, cmd/gpu-feature-discovery/main_test.go, cmd/gpu-feature-discovery/mig_test.go, internal/flags/node.go, internal/lm/output.go
The `node-name` is only needed if the NodeFeatureAPI is used.
=> Don't require node-name to be set if not needed

deployments/helm/nvidia-device-plugin/templates/_helpers.tpl, deployments/helm/nvidia-device-plugin/templates/daemonset-device-plugin.yml, deployments/helm/nvidia-device-plugin/templates/daemonset-gfd.yml, deployments/helm/nvidia-device-plugin/templates/daemonset-mps-control-daemon.yml, deployments/helm/nvidia-device-plugin/templates/role-binding.yml, deployments/helm/nvidia-device-plugin/templates/role.yml, deployments/helm/nvidia-device-plugin/templates/service-account.yml
The helm include statement always generates a string. This was leading to inconsistent handling of the hasConfigMap option.
This change adds a options helper that can be used to pass derrived values as JSON so that the type information is retained when including these.
Fixes #689
=> Fix usage of hasConfigMap

deployments/helm/nvidia-device-plugin/templates/daemonset-device-plugin.yml, deployments/helm/nvidia-device-plugin/templates/daemonset-gfd.yml, deployments/helm/nvidia-device-plugin/templates/daemonset-mps-control-daemon.yml
It's generally recommended to use the `quote` function instead of explicitly wrapping helm values with quotes in-line
=> use the helm quote function to wrap boolean values in quotes

deployments/helm/nvidia-device-plugin/templates/_helpers.tpl, deployments/helm/nvidia-device-plugin/templates/daemonset-device-plugin.yml, deployments/helm/nvidia-device-plugin/templates/daemonset-gfd.yml, deployments/helm/nvidia-device-plugin/templates/daemonset-mps-control-daemon.yml
`configMapName` is the empty string `""` by default and it breaks `allPossibleMigStrategiesAreNone` function with default values.
See https://github.com/NVIDIA/k8s-device-plugin/issues/670 for details.
=> Fixing allPossibleMigStrategiesAreNone helm chart helper.

deployments/container/Makefile
Tools such as oc mirror do not support the provenence metadata added to the image manifests with newer docker buildx versions.
This change disables the addition of provenance information.
=> Remove provenance information from image manifests

api/config/v1/flags.go, api/config/v1/flags_test.go, cmd/gpu-feature-discovery/main.go, cmd/gpu-feature-discovery/main_test.go, cmd/nvidia-device-plugin/main.go, deployments/helm/nvidia-device-plugin/templates/daemonset-device-plugin.yml, deployments/helm/nvidia-device-plugin/templates/daemonset-gfd.yml, deployments/helm/nvidia-device-plugin/values.yaml, internal/plugin/manager/factory.go, internal/resource/factory.go
This change adds a device-discovery-strategy flag to the device plugin (as was done for GFD in #676). This allows the platform detection to be overridden using the corresponding `devicePlugin.mode` helm value or `DEVICE_DISCOVERY_STRATEGY` envvar.
The default of "auto" follows the previous behaviour.
Depends on #730
=> Allow device-discovery-strategy to be specified

cmd/mps-control-daemon/main.go, cmd/mps-control-daemon/mount/mount-shm.go
This change reads MemTotal from /proc/meminfo and sets
the dev/shm size to half this value. This aligns with the
default for creating tmpfs mounts.
If reading the value fails, the previous default of 65536k is used.
=> Set /dev/shm size from /proc/meminfo

api/config/v1/config.go, api/config/v1/flags.go, api/config/v1/strategy.go, cmd/nvidia-device-plugin/main.go, cmd/nvidia-device-plugin/plugin-manager.go, cmd/nvidia-device-plugin/root.go, deployments/helm/nvidia-device-plugin/templates/daemonset-device-plugin.yml, deployments/helm/nvidia-device-plugin/values.yaml, internal/cdi/cdi.go, internal/cdi/options.go, internal/plugin/server.go
Thes changes add support to the NVIDIA GPU Device Plugin for driver
installations that have the following properties:
* driver files are installed at a `hostDriverRoot`, say: `/host/nvidia/driver`
* device nodes are created at `/dev`
In addition to the mounts of driver libraries (e.g. `libnvidia-ml.so.VERSION`)
and device nodes that are handled by the NVIDIA Container Runtime or CDI to
allow the device plugin to detect and enumerate devices, the `hostDriverRoot`
is mounted into the device plugin at `/driver-root`. This allows the detection
of driver files that are not required for the device plugin to fuction, but may
be required by specific workloads.
From the perspective of the CDI spec generation being run in the device plugin
container, all driver files are rooted at `/driver-root`. …
=> Support non-standard driver installs

versions.mk
This is requried to address https://nvd.nist.gov/vuln/detail/CVE-2024-24790
=> Bump golang to 1.22.4

.github/dependabot.yml, .github/workflows/golang.yaml, Makefile, demo/clusters/kind/scripts/build-plugin-image.sh, deployments/devel/Dockerfile, deployments/devel/Makefile, deployments/devel/go.mod, deployments/devel/go.sum, deployments/devel/tools.go
This change manages tooling dependencies using go instead of relying on the k8s-test-infra image.
This allows for the image and tooling dependencies to be updated independently.
=> Use go to manage build image dependencies

.github/dependabot.yml, .github/workflows/golang.yaml, hack/golang-version.sh, versions.mk
This change uses Dependabot to update the golang toolcain.
The `deployments/devel/Dockfile` is used as a reference for defining the golang version through the `FROM` clause.
=> [no-relnotes] Use dependabot to update go toolchain

internal/plugin/server.go
=> Use WithContextDialer to replace WithDialer

.github/dependabot.yml, CHANGELOG.md, README.md, deployments/helm/nvidia-device-plugin/Chart.yaml, deployments/static/gpu-feature-discovery-daemonset-with-mig-mixed.yaml, deployments/static/gpu-feature-discovery-daemonset-with-mig-single.yaml, deployments/static/gpu-feature-discovery-daemonset.yaml, deployments/static/gpu-feature-discovery-job.yaml.template, deployments/static/nvidia-device-plugin-compat-with-cpumanager.yml, deployments/static/nvidia-device-plugin.yml, versions.mk
This cherry-picks the version bumps from #827 to `main`.
=> Bump version to v0.16.0 on main

go.mod, go.sum, vendor/github.com/NVIDIA/nvidia-container-toolkit/internal/platform-support/dgpu/nvml.go, vendor/modules.txt
This fixes a bug with processing errors during CDI spec generation for MIG devices.
=> Bump nvidia-container-toolkit to v1.16.1

.github/workflows/e2e.yaml
By moving away from "main", we will now gain Dependabot updates to Holodeck action version
=> [no-relnote] Bump Holodeck to v0.2.1

tests/e2e/Makefile
This PR enables E2E after https://github.com/NVIDIA/k8s-device-plugin/pull/855
=> [no-relnote] Change context during E2E call

tests/e2e/device-plugin_test.go
The device plugin e2e tests regularly fail due to a timeout of 5 minutes:
```
[FAILED] Timed out after 300.001s.
```
This introduced flakiness into the tests. 
This change increased the timeout for the device plugin job checks to 10 minutes instead.
=> [no-relnote] Increase timeout for GPU job test to 10 minutes

deployments/container/Dockerfile
As the go.mod file pins the minimum go version to 1.22.2, it no longer makes sense for the container's default go version to be a values lesser than that. Sp we bump the default golang build arg to 1.22.6
Signed-off-by: Tariq Ibrahim <tibrahim@nvidia.com>
=> update default go version of the main container image

tests/e2e/Makefile
With these long running tests, the default gotest timeout of 10 mintues is too short.
=> [no-relnotes] Increase timeout for e2e tests

.github/workflows/staging_e2e.yaml
With https://github.com/NVIDIA/k8s-device-plugin/pull/884 we removed the ubuntu22.04 images.
This change uses the ubi8 images since these are now the only images.
=> [no-relnote] Use ubi8 image in tests

deployments/container/Dockerfile, deployments/container/cleanup/cleanup.sh
These changes apply a set of transforms / cleanups to the CUDA ubi8 base to remove unneeded packages.
=> Use reduced ubi8 base image

cmd/mps-control-daemon/mps/daemon.go, go.mod, vendor/github.com/opencontainers/selinux/LICENSE, vendor/github.com/opencontainers/selinux/go-selinux/doc.go, vendor/github.com/opencontainers/selinux/go-selinux/selinux.go, vendor/github.com/opencontainers/selinux/go-selinux/selinux_linux.go, vendor/github.com/opencontainers/selinux/go-selinux/selinux_stub.go, vendor/github.com/opencontainers/selinux/go-selinux/xattrs_linux.go, vendor/github.com/opencontainers/selinux/pkg/pwalkdir/README.md, vendor/github.com/opencontainers/selinux/pkg/pwalkdir/pwalkdir.go, vendor/modules.txt
Use `github.com/opencontainers/selinux/go-selinux` instead of calling the `chcon` command to set SELinux context.
This PR builds upon #789, but according to opencontainers/selinux/issues/215, a full label must be applied when using the SELinux Go package. Also, checking whether SELinux is available has been changed - the reason was discussed in detail in #847.
=> Use SELinux package to apply context

.golangci.yml, api/config/v1/replicas.go, internal/cuda/api.go, internal/rm/health.go, internal/vgpu/pciutil.go, internal/vgpu/vgpu.go
=> [no-relnote] Address integer overflow linting errors

internal/lm/nvml.go, internal/resource/cuda-lib.go, internal/resource/fallback.go, internal/resource/manager_mock.go, internal/resource/null.go, internal/resource/nvml-lib.go, internal/resource/nvml-mig-device.go, internal/resource/sysfs-lib.go, internal/resource/testing/resource-testing.go, internal/resource/types.go
This PR makes the following changes to address `golangci-lint` errors:
* updates the `GetCudaDriverVersion` return type to `(int, int, error)` instead of `(*uint, *uint, error)`. This prevents unneeded type conversions and pointer operations.
* adds an explicit check in the testing-only `int` -> `uint64` type conversion for MIG memory.
=> Fix golang-ci-lint errors

cmd/nvidia-device-plugin/main.go, cmd/nvidia-device-plugin/plugin-manager.go, internal/plugin/manager/factory.go, internal/plugin/manager/nvml.go, internal/plugin/manager/options.go, internal/plugin/manager/tegra.go, internal/plugin/server.go
This also makes it possible to test device plugin logic that does not depend on the kubelet.
=> Accept kubelet socket from command line

deployments/container/native-only.mk
This changes allows the image architecture to be specified when building a "native" image. This is usefull when testing accross architectures.
=> [no-relnote] Allow ARCH to be specified for single image

internal/plugin/server.go
This change fixes an incorrect HostPath for IMEX channels when passing device specs as part of the ContainerAllocateResponse.
=> Fix IMEX injection when passing device nodes

internal/plugin/server.go, internal/rm/rm.go
- modify the log level of some errors
- fix method comment
=> modify the log level of some errors

deployments/helm/nvidia-device-plugin/templates/role-binding.yml, deployments/helm/nvidia-device-plugin/templates/role.yml
See:
* https://kubernetes.io/docs/reference/access-authn-authz/rbac/#clusterrole-example
* https://kubernetes.io/docs/reference/access-authn-authz/rbac/#clusterrolebinding-example
=> Remove namespace field from cluster-scoped `ClusterRole` and `ClusterRoleBinding` resources

.github/workflows/code_scanning.yaml
By default, CodeQL uses a rather old version of Go. We should use the same Go version across all CI pipelines.
=> align the go version used in codeQL with the devel images

internal/lm/fabric.go, internal/lm/fabric_test.go
~Here is a [post](https://go.dev/blog/randv2) that goes into detail on the security limitations of the `math/rand` package.~
~Since the IMEX changes haven't publicised yet, I thought this would be a safe starting point to implement this change~
=> use uuid.NewSHA1 package to generate uuids

deployments/container/cleanup/cleanup.sh
This change adds the mount utility to the minimal image used by the device plugin and GFD. This is needed to set up the mounts for the MPS control daemon.
This was removed in #813
=> Add mount utility to minimal image

CHANGELOG.md, README.md, deployments/helm/nvidia-device-plugin/Chart.yaml, deployments/static/gpu-feature-discovery-daemonset-with-mig-mixed.yaml, deployments/static/gpu-feature-discovery-daemonset-with-mig-single.yaml, deployments/static/gpu-feature-discovery-daemonset.yaml, deployments/static/gpu-feature-discovery-job.yaml.template, deployments/static/nvidia-device-plugin-compat-with-cpumanager.yml, deployments/static/nvidia-device-plugin.yml, versions.mk
This bumps the versions on `main` following the `v0.17.0` release.
See #1028
=> Bump release v0.17.0

.github/workflows/publish-helm.yaml, hack/update-helm-index.sh
This prevents errors such as https://github.com/NVIDIA/k8s-device-plugin/actions/runs/11615138763 in the publish-helm action.
=> [no-relnote] Set git user name and email in subfolder repo

Makefile
This adds a check to go submodules to ensure that these are also up to date.
=> [no-relnote] Check go submodules

cmd/gpu-feature-discovery/main.go, internal/resource/factory.go
As implemented GFD will not fail if no resources are detected -- even if fail-on-init-error is set. This change ensures that fail-on-init-error is honored if no resources are detected.
=> Honor fail-on-init-error when no resources are found

internal/lm/nvml.go
For environments like WSL2 where GPUs do not show up as PCI devices, creating the GPU mode labeler will fail. This change allows GFD to proceed even if it is unable to get the GPU mode label.
=> Raise a warning instead of an error if GPU mode labeler fails

README.md
as cri docker has merged 
https://github.com/Mirantis/cri-dockerd/pull/350
this pr
then runtime can pass rightadble, we do not must set default runtime in docker
=> do not need to set default runtime nvidia in docker 

internal/rm/health.go
This change adds XID error 109 to the list of ignored errors.
=> Ignore XID error 109

.nvidia-ci.yml
The pulse scanner logs are output to pulse-cli.log and not pulse-cli.logs
=> [no-relnote] Fix GitLab Pipeline artifact names

CHANGELOG.md, README.md, deployments/helm/nvidia-device-plugin/Chart.yaml, deployments/static/gpu-feature-discovery-daemonset-with-mig-mixed.yaml, deployments/static/gpu-feature-discovery-daemonset-with-mig-single.yaml, deployments/static/gpu-feature-discovery-daemonset.yaml, deployments/static/gpu-feature-discovery-job.yaml.template, deployments/static/nvidia-device-plugin-compat-with-cpumanager.yml, deployments/static/nvidia-device-plugin.yml, versions.mk
These changes ensure that the documentation and static charts on `main` refer to the latest release.
This cherry-picks the changes from #1194
=> Bump versions to v0.17.1 post-release

.common-ci.yml
In order to publish projects with NGC Publishing Configs, the images will need to be staged in the nvstaging registry. This change updates the variables in .release:staging to refer to the NGC registry.
=> Updated .release:staging to stage device-plugin images in nvstaging

internal/lm/resource.go
Confirmed that the blackwell architecture corresponds to cuda compute with major number 10.
With the fix, we print the "blackwell" label value instead of "undefined"
=> [gpu-feature-discovery] detect blackwell architecture

deployments/static/nvidia-device-plugin-compat-with-cpumanager.yml, deployments/static/nvidia-device-plugin.yml
This change removes FAIL_ON_INIT_ERROR=false from the static examples. This is a non-recommended setting as failures in loading GPU information is silently ignored.
See https://nvbugspro.nvidia.com/bug/5129637
=> Remove FAIL_ON_INIT_ERROR from static examples

deployments/helm/nvidia-device-plugin/templates/daemonset-device-plugin.yml, deployments/helm/nvidia-device-plugin/templates/daemonset-gfd.yml, deployments/static/gpu-feature-discovery-daemonset-with-mig-mixed.yaml, deployments/static/gpu-feature-discovery-daemonset-with-mig-single.yaml, deployments/static/gpu-feature-discovery-daemonset.yaml, deployments/static/gpu-feature-discovery-job.yaml.template, deployments/static/nvidia-device-plugin-compat-with-cpumanager.yml, deployments/static/nvidia-device-plugin-privileged-with-service-account.yml, deployments/static/nvidia-device-plugin.yml
This change ensures that volumes that are expected to be directories have a Directory or DirectoryOrCreate type.
See https://nvbugspro.nvidia.com/bug/5129540
=> Ensure that directory volumes have Directory type

internal/lm/resource.go, internal/rm/devices.go
On certain systems (e.g. iGPU-based systems), the NVML nvmlDeviceGetMemoryInformation API
is not supported and returns an error. In these cases we ignore
these errors and log a warning instead. This means that:
* For the GPU Device Plugin, memory limits will be enforced for MPS partioning.
* For GFD, no nvidia.com/gpu.memory label will be generated.
=> Ignore errors getting optional device attributes

internal/plugin/server.go
Looks like there is some typo in the go doc comment for `func (plugin *nvidiaDevicePlugin) Allocate`. This PR tries to fix it.
=> Correct go doc comment for `func (plugin *nvidiaDevicePlugin) Allocate`
